### PR TITLE
Fix in CGAL package Installation

### PR DESCRIPTION
**Pull request by mhsaar**
Fix in CGAL package Installation

### CODE REVIEW

**Comment by afabri** [comment]
I would prefer to see the `defined( YET_ANOTHER_ARCHITECTURE) ` added instead of a default endianness.  With what architecture did you hit this problem  (unless it reveals a top secret).

**Comment by sloriot** [comment]
We can also add a macro like `CGAL_DEFAULT_ENDIANESS` that would define it and avoid the error.

**Comment by mhsaar** [comment]
The DEFAULT solution would be best. 
And I am afraid there is no top secrete architecture. I just can't run cmake to determine what's going on. 

We essentially use https://bazel.build/

**Comment by sloriot** [comment]
Replaced by https://github.com/CGAL/cgal/pull/4281

**Pull request closed without merging**
